name: buildmatch
description: "BuildMatch - Marketplace Jasa Konstruksi"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State management (simple & clean)
  provider: ^6.1.2

  # Format tanggal (progress proyek, dll)
  intl: ^0.19.0

  # Generate ID unik (project id, dll)
  uuid: ^4.4.0

  # UI icons tambahan
  flutter_svg: ^2.0.10
  supabase_flutter: ^2.12.4
  image_picker: ^1.2.1
  file_picker: ^8.0.7
  flutter_map: ^8.3.0
  latlong2: ^0.9.1

  # Buka URL eksternal (PDF referensi, Google Maps, dll)
  url_launcher: ^6.3.1
  http: ^1.6.0
  crop_your_image: ^2.0.0
  shared_preferences: ^2.5.5
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/ui/client/assets/images/house_styles/
